### ISSUE TITLE
ツイートとのロジックエラー？

### ISSUE THREAD

**Issue by Krout0n** [takehaya/takehaya.github.io#1]
すみません，敵意とか矛盾を突っつきたいとか揚げ足とりたいとかそういうわけじゃないんですけど，このコミットをした後にどのような心境でこのツイートをしたのか教えていただけると安眠できそうなので良かったら教えて頂けると嬉しいです．

本当に煽っているつもりも矛盾してるから該当箇所を消せというつもりもなくて，気になりすぎて寝れなくなって困っているので良かったらお願いいたします．

自分が寝れなくなるぐらいならissueを立ててしまおうという気持ちで立ててしまいました．不快な気持ちにさせてしまったら大変申し訳ございません．

https://twitter.com/takemioIO/status/1012034190391431169
https://github.com/takehaya/takehaya.github.io/commit/0c2ea04aafca5ff3c81cc174cafb8e5915e951e0#diff-eacf331f0ffc35d4b482f1d15a887d3bR91

**Comment by Krout0n** [comment]
立てたら寝れたので大丈夫です，ご迷惑をおかけしてすみませんでした・・・

**Comment by takehaya** [comment]
完全に不要なissueを立てるとか煽りにしか見えないのですが（流石にcommitのお気持ちとかリプライかDMで聞いて欲しい内容感がある），クローズされて気がつかなったせいか先ほどこの当該issueを見てしまったのでお答えします．

まず質問の話として
> このコミットをした後にどのような心境でこのツイートをしたのか教えて

これは単純なイキリです．深夜3:05 - 2018年6月28日にしているのを見るとわかる通り深夜のイキリですね．

まぁこれだけだとわからないので背景も含め色々説明すると．．．
そもそもこのプロフィールリンクは何かと言うと僕の名刺交換した先にあるQRのリンクなのです．自分の専門分野が固まってないので何をやってきて何が好きなのかを説明する話のタネにするものした．
twiiterにリンクになってますが，そもそも昔はリンクがブログだったのです．ですがそのブログはあんまり更新しなかったりなど他にも事情があり，このリンクに変えていました．

また，前後のツイートなど確認すると
https://twitter.com/takemioIO/status/1012038041475547136
などがあります．というように別にキャンパーである事をdisってるわけでもなければ人によって（しってほしいからとか）つける理由もあるので自分は別にどうでもいいんですよね．そもそもとしてこれは持論であると書いていて，なおかつこれは深夜帯というゾーイングをしてたのですがまさかのここだけ「RTられて」しまったというのがあります．

なので個人的なお気持ちとしては，貴方を不快にして申し訳ないのだが「これは意図せず勝手に不快になってしまっただけ」っていう気持ちがあってですね．ここだけのスナップショットを見ないでなおかつ他の手段で聞いていただけるとよかったなと思います．

**Comment by Krout0n** [comment]
こんにちは，ご丁寧にご返信ありがとうございます．その節は大変申し訳ございませんでした．完全に当時は深夜で頭が回ってなく，明らかに不適切な手段であるIssueを立てるなどをしてしまいました．深夜の1ツイートに対して必要以上に噛み付いた僕が悪いと思っています．ご迷惑をおかけしてすみませんでした．
